In [1]:
import mne
import numpy as np

In [2]:
data = mne.io.read_raw_edf('Splitted Files/eeg_19/eeg19_1.edf', preload=True)

Extracting EDF parameters from /home/anjali/Desktop/Mehnat/BTP2/Splitted Files/eeg_19/eeg19_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 255  =      0.000 ...     0.996 secs...


In [3]:
import pyeeg as p
df = data.to_data_frame()
p.dfa(df)

Converting "time" to "<class 'numpy.int64'>"...


/home/anjali/Desktop/Mehnat/BTP2/pyeeg.py:858: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  Alpha = lstsq(vstack([log(L), ones(len(L))]).T,log(F))[0][0]


0.0

In [4]:
def bp(X, Band, Fs):
    C = np.fft.fft(X)
    C = abs(C)
    print(C.shape)
    Power = np.zeros(len(Band)-1);
    for Freq_Index in range(0,len(Band)-1):
        Freq = float(Band[Freq_Index])
        Next_Freq = float(Band[Freq_Index+1])
        # print(Freq, Next_Freq)
        power_Calc = 0
        left_lim = (int)(Freq)
        right_lim = (int)(Next_Freq)
        for row in range(left_lim, right_lim):
            for col in range(21):
                power_Calc += C[row][col]
        Power[Freq_Index] = power_Calc
    Power_Ratio = Power/sum(Power)
    return Power, Power_Ratio

In [5]:
bands = [0.5,4,8,12,30]
power, power_ratio = bp(df, bands, 256)
p.spectral_entropy(df, bands, 256, power_ratio)

(256, 21)


0.5816357028004554

In [6]:
bp(df, [0.5,4,8], 256)

(256, 21)


(array([6624.72186014, 6994.25209897]), array([0.48643326, 0.51356674]))

In [7]:
from scipy.stats import norm, kurtosis
data = mne.io.read_raw_edf('Splitted Files/eeg_19/eeg19_1.edf', preload=True)
df = data.to_data_frame()
kurtosis(df)

Extracting EDF parameters from /home/anjali/Desktop/Mehnat/BTP2/Splitted Files/eeg_19/eeg19_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 255  =      0.000 ...     0.996 secs...
Converting "time" to "<class 'numpy.int64'>"...


array([-0.72482078, -0.20852317,  0.47884753,  0.38021414, -0.49961771,
        0.14039217,  0.49252372,  1.17942071,  1.04518653, -0.13852615,
       -1.07036504, -0.98133975, -0.18341055, -0.5701919 , -0.98858092,
        1.2259489 ,  0.53852739, -0.72421795,  1.04034628, 19.03535807,
        0.53842011])

In [47]:
from scipy.stats import skew
skewness = skew(df)
skewness

array([-0.41640542, -0.56745396, -0.86234257,  0.96047427, -0.34953751,
       -0.80006874,  0.33503172, -1.36104782, -0.95199763,  0.03802309,
        0.27396718,  0.27291101, -0.85145592, -0.34704866,  0.3872629 ,
       -1.23198798, -0.90844067, -0.02452692, -0.78706303,  3.90046816,
       -1.16824142])

In [48]:
# VARIANCE

np.var(df)

channel
EEG Fp1-Ref      449.850149
EEG Fp2-Ref      196.067765
EEG F3-Ref       192.528918
EEG F4-Ref       147.656153
EEG F7-Ref       940.473934
EEG F8-Ref       196.640905
EEG Fz-Ref       245.081693
EEG C3-Ref       116.810146
EEG C4-Ref        92.414149
EEG Cz-Ref         0.052736
EEG T3-Ref       759.685507
EEG T5-Ref       573.475276
EEG T4-Ref       207.853473
EEG T6-Ref        91.346572
EEG P3-Ref       164.936571
EEG P4-Ref        68.353308
EEG Pz-Ref        70.670657
EEG O1-Ref       107.668264
EEG O2-Ref        99.600877
ECG EKG        11407.199259
Resp Effort        0.790360
dtype: float64

In [56]:
variance_vals = np.var(df)
pooled_var = 0
sample_size = len(df)
num_channels = df.shape[1]

for val in variance_vals:
    pooled_var += (sample_size - 1) * val
pooled_var = pooled_var/((sample_size*num_channels) - num_channels)
pooled_var

768.0550796262354

In [21]:
df.columns

Index(['EEG Fp1-Ref', 'EEG Fp2-Ref', 'EEG F3-Ref', 'EEG F4-Ref', 'EEG F7-Ref',
       'EEG F8-Ref', 'EEG Fz-Ref', 'EEG C3-Ref', 'EEG C4-Ref', 'EEG Cz-Ref',
       'EEG T3-Ref', 'EEG T5-Ref', 'EEG T4-Ref', 'EEG T6-Ref', 'EEG P3-Ref',
       'EEG P4-Ref', 'EEG Pz-Ref', 'EEG O1-Ref', 'EEG O2-Ref', 'ECG EKG',
       'Resp Effort'],
      dtype='object', name='channel')

In [52]:
len(df)

256

In [35]:
col1 = df['EEG Fp1-Ref']
col1_numpy = col1.to_numpy()
col1_numpy.shape
p.hurst(col1_numpy)

0.7932692144653476

In [42]:
df_np = df.to_numpy()
p.pfd(col1_numpy)

0.6375296173752467

In [46]:
p.hjorth(col1_numpy)

(0.004476078182613001, 190.14627844358685)