In [1]:
import numpy as np
import matplotlib.pyplot as plt

import mne

In [2]:
data = mne.io.read_raw_edf('Splitted Files/eeg_19/eeg19_1.edf', preload=True)

Extracting EDF parameters from /home/anjali/Desktop/Mehnat/BTP2/Splitted Files/eeg_19/eeg19_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 255  =      0.000 ...     0.996 secs...


In [3]:
import pyeeg as p
df = data.to_data_frame()
p.dfa(df)
# Power[Freq_Index] = sum(C[floor(Freq/Fs*len(X)):floor(Next_Freq/Fs*len(X))])

Converting "time" to "<class 'numpy.int64'>"...


/home/anjali/Desktop/Mehnat/BTP2/pyeeg.py:858: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  Alpha = lstsq(vstack([log(L), ones(len(L))]).T,log(F))[0][0]


0.0

In [4]:
for row in range(20):
    row_to_add = []
    data = mne.io.read_raw_edf('./Splitted Files/eeg_68/68.{}.edf'.format(row+1), preload=True)
    data = data[:][0]
    print(p.dfa(data))
    print("\n")

Extracting EDF parameters from /home/anjali/Desktop/Mehnat/BTP2/Splitted Files/eeg_68/68.1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 255  =      0.000 ...     0.996 secs...
0.0


Extracting EDF parameters from /home/anjali/Desktop/Mehnat/BTP2/Splitted Files/eeg_68/68.2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 255  =      0.000 ...     0.996 secs...
0.0


Extracting EDF parameters from /home/anjali/Desktop/Mehnat/BTP2/Splitted Files/eeg_68/68.3.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 255  =      0.000 ...     0.996 secs...
0.0


Extracting EDF parameters from /home/anjali/Desktop/Mehnat/BTP2/Splitted Files/eeg_68/68.4.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 255  =      0.000 ...     0.996 secs...
0.0


Extracting EDF parameters from /home

In [5]:
def bp(X, Band, Fs):
    C = np.fft.fft(X)
    C = abs(C)
    print(C.shape)
    Power = np.zeros(len(Band)-1);
    for Freq_Index in range(0,len(Band)-1):
        Freq = float(Band[Freq_Index])
        Next_Freq = float(Band[Freq_Index+1])
        # print(Freq, Next_Freq)
        power_Calc = 0
        left_lim = (int)(Freq)
        right_lim = (int)(Next_Freq)
        for row in range(left_lim, right_lim):
            for col in range(21):
                power_Calc += C[row][col]
        Power[Freq_Index] = power_Calc
    Power_Ratio = Power/sum(Power)
    return Power, Power_Ratio

In [6]:
bp(df, [0.5,4,8,12,30], 256)

(256, 21)


(array([ 6624.72186014,  6994.25209897,  7214.19580129, 31172.35822796]),
 array([0.12738496, 0.13449055, 0.13871979, 0.59940471]))

In [7]:
arr = np.zeros(5)
arr[0] = 5
arr
Band = [0.5,4,7]
Freq = float(Band[0])
(int)(Freq)

0

In [8]:
l = np.array([[2,3],[3,5],[4,9]])
l.shape

(3, 2)

In [9]:
sum(l[1:2])

array([3, 5])

In [10]:
np.fft.fft(df).shape

(256, 21)