In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Combined-780 - Sheet1.csv')
data

Signal   Mean (µV)     RMS (µV)     MRS (µV)  Zero Crossings  \
0        e1.1 -111.543263   165.326922   137.464510               6   
1        e1.2  -85.046038   140.633143   111.886389               6   
2        e1.3  -46.838299   126.812428    85.819704              16   
3        e1.4  -47.013536   143.652350    91.850550               7   
4        e1.5  -15.339653   113.011520    53.273050              24   
..        ...         ...          ...          ...             ...   
775  e47.1.16 -492.032900   791.292300   693.099200               3   
776  e47.1.17 -255.891500   455.610800   378.904600               4   
777  e47.1.18  224.316200   619.768200   541.530000               8   
778  e47.1.19 -164.945500   986.025200   798.400200               4   
779  e47.1.20 -385.829500  1501.861800  1148.949700               3   

     Frequency (Hz)  Delta (µV² /Hz)  Theta (µV² /Hz)  Alpha (µV² /Hz)  \
0               3.0        13.871195         0.216515         0.157400   
1               3.0         5.126801         0.176441         0.151454   
2               8.0         1.261876         0.181805         0.161871   
3               3.5         0.899144         0.212408         0.298429   
4              12.0         0.423585         0.195163         0.150992   
..              ...              ...              ...              ...   
775             1.5        34.918747         2.114091         0.244951   
776             2.0        15.347951         1.263933         0.188982   
777             4.0        24.577597         0.953114         0.249922   
778             2.0        31.002390         1.905827         0.262337   
779             1.5        63.294042         3.625288         0.130177   

     Beta (µV² /Hz)  Gamma (µV² /Hz)  Label  
0          0.471267         0.360638      0  
1          0.471898         0.364846      0  
2          0.472354         0.372668      0  
3          0.738894         0.501854      0  
4          0.484105         0.371071      0  
..              ...              ...    ...  
775        0.139495         0.062960      1  
776        0.112097         0.051938      1  
777        0.139794         0.061432      1  
778        0.121908         0.053995      1  
779        0.113923         0.049579      1  

[780 rows x 12 columns]

In [3]:
X = data.drop(columns=['Signal','Label'])
y = data['Label']

In [4]:
import numpy as np
np.isnan(X).any()

Mean (µV)          False
RMS (µV)           False
MRS (µV)           False
Zero Crossings     False
Frequency (Hz)     False
Delta (µV² /Hz)    False
Theta (µV² /Hz)    False
Alpha (µV² /Hz)    False
Beta (µV² /Hz)     False
Gamma (µV² /Hz)    False
dtype: bool

In [5]:
X.loc[[2,3,4,50]]
from sklearn.metrics import confusion_matrix

In [22]:
from sklearn.model_selection import KFold
from sklearn import svm
from sklearn import preprocessing as pre

kf = KFold(n_splits=7)
acc = []
sens = []
spec = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    model = svm.SVC(kernel='linear',C=20).fit(X_train_scaled, y_train)
    score = model.score(X_test_scaled, y_test)
    y_pred = model.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(accuracy1)
    sens.append(sensitivity1)
    spec.append(specificity1)
    
print(max(acc))

Confusion Matrix : 
 [[63 29]
 [ 6 14]]
Accuracy :  0.6875
Sensitivity :  0.684782608696
Specificity :  0.7
Confusion Matrix : 
 [[36 32]
 [32 12]]
Accuracy :  0.428571428571
Sensitivity :  0.529411764706
Specificity :  0.272727272727
Confusion Matrix : 
 [[34  2]
 [72  4]]
Accuracy :  0.339285714286
Sensitivity :  0.944444444444
Specificity :  0.0526315789474
Confusion Matrix : 
 [[41  3]
 [ 9 58]]
Accuracy :  0.891891891892
Sensitivity :  0.931818181818
Specificity :  0.865671641791
Confusion Matrix : 
 [[50 28]
 [ 6 27]]
Accuracy :  0.693693693694
Sensitivity :  0.641025641026
Specificity :  0.818181818182
Confusion Matrix : 
 [[44  7]
 [38 22]]
Accuracy :  0.594594594595
Sensitivity :  0.862745098039
Specificity :  0.366666666667
Confusion Matrix : 
 [[63  8]
 [29 11]]
Accuracy :  0.666666666667
Sensitivity :  0.887323943662
Specificity :  0.275
0.891891891892


In [23]:
from sklearn.neighbors import KNeighborsClassifier

kf = KFold(n_splits=8)
acc = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    knn = KNeighborsClassifier(n_neighbors=5).fit(X_train_scaled, y_train)
    score = knn.score(X_test_scaled, y_test)
    y_pred = knn.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(accuracy1)

# mean_acc = sum(acc)/len(acc)
# mean_sens = sum(sens)/len(sens)
# mean_spec = sum(spec)/len(spec)
print(max(acc))

Confusion Matrix : 
 [[21 57]
 [ 9 11]]
Accuracy :  0.326530612245
Sensitivity :  0.269230769231
Specificity :  0.55
Confusion Matrix : 
 [[33 25]
 [14 26]]
Accuracy :  0.602040816327
Sensitivity :  0.568965517241
Specificity :  0.65
Confusion Matrix : 
 [[18  6]
 [40 34]]
Accuracy :  0.530612244898
Sensitivity :  0.75
Specificity :  0.459459459459
Confusion Matrix : 
 [[28 32]
 [23 15]]
Accuracy :  0.438775510204
Sensitivity :  0.466666666667
Specificity :  0.394736842105
Confusion Matrix : 
 [[15 34]
 [25 23]]
Accuracy :  0.39175257732
Sensitivity :  0.30612244898
Specificity :  0.479166666667
Confusion Matrix : 
 [[47  4]
 [16 30]]
Accuracy :  0.79381443299
Sensitivity :  0.921568627451
Specificity :  0.652173913043
Confusion Matrix : 
 [[29 34]
 [10 24]]
Accuracy :  0.546391752577
Sensitivity :  0.460317460317
Specificity :  0.705882352941
Confusion Matrix : 
 [[45 12]
 [28 12]]
Accuracy :  0.587628865979
Sensitivity :  0.789473684211
Specificity :  0.3
0.79381443299


In [24]:
from sklearn.neighbors import KNeighborsClassifier
kf = KFold(n_splits=8)
acc = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    knn = KNeighborsClassifier(n_neighbors=10).fit(X_train_scaled, y_train)
    score = knn.score(X_test_scaled, y_test)
    y_pred = knn.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(accuracy1)

# mean_acc = sum(acc)/len(acc)
# mean_sens = sum(sens)/len(sens)
# mean_spec = sum(spec)/len(spec)
print(max(acc))

Confusion Matrix : 
 [[25 53]
 [12  8]]
Accuracy :  0.336734693878
Sensitivity :  0.320512820513
Specificity :  0.4
Confusion Matrix : 
 [[36 22]
 [19 21]]
Accuracy :  0.581632653061
Sensitivity :  0.620689655172
Specificity :  0.525
Confusion Matrix : 
 [[22  2]
 [45 29]]
Accuracy :  0.520408163265
Sensitivity :  0.916666666667
Specificity :  0.391891891892
Confusion Matrix : 
 [[37 23]
 [26 12]]
Accuracy :  0.5
Sensitivity :  0.616666666667
Specificity :  0.315789473684
Confusion Matrix : 
 [[23 26]
 [25 23]]
Accuracy :  0.474226804124
Sensitivity :  0.469387755102
Specificity :  0.479166666667
Confusion Matrix : 
 [[46  5]
 [18 28]]
Accuracy :  0.762886597938
Sensitivity :  0.901960784314
Specificity :  0.608695652174
Confusion Matrix : 
 [[40 23]
 [17 17]]
Accuracy :  0.587628865979
Sensitivity :  0.634920634921
Specificity :  0.5
Confusion Matrix : 
 [[47 10]
 [32  8]]
Accuracy :  0.567010309278
Sensitivity :  0.824561403509
Specificity :  0.2
0.762886597938


In [29]:
from sklearn.linear_model import LogisticRegression

kf = KFold(n_splits=8)
acc = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    mod = LogisticRegression(random_state=0,max_iter=1000).fit(X_train_scaled, y_train)
    score = mod.score(X_test_scaled, y_test)
    y_pred = mod.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(accuracy1)
    
# mean_acc = sum(acc)/len(acc)
# mean_sens = sum(sens)/len(sens)
# mean_spec = sum(spec)/len(spec)
print(max(acc))

Confusion Matrix : 
 [[45 33]
 [ 9 11]]
Accuracy :  0.571428571429
Sensitivity :  0.576923076923
Specificity :  0.55
Confusion Matrix : 
 [[40 18]
 [26 14]]
Accuracy :  0.551020408163
Sensitivity :  0.689655172414
Specificity :  0.35
Confusion Matrix : 
 [[ 4 20]
 [50 24]]
Accuracy :  0.285714285714
Sensitivity :  0.166666666667
Specificity :  0.324324324324
Confusion Matrix : 
 [[41 19]
 [25 13]]
Accuracy :  0.551020408163
Sensitivity :  0.683333333333
Specificity :  0.342105263158
Confusion Matrix : 
 [[39 10]
 [25 23]]
Accuracy :  0.639175257732
Sensitivity :  0.795918367347
Specificity :  0.479166666667
Confusion Matrix : 
 [[49  2]
 [16 30]]
Accuracy :  0.814432989691
Sensitivity :  0.960784313725
Specificity :  0.652173913043
Confusion Matrix : 
 [[42 21]
 [19 15]]
Accuracy :  0.587628865979
Sensitivity :  0.666666666667
Specificity :  0.441176470588
Confusion Matrix : 
 [[48  9]
 [29 11]]
Accuracy :  0.60824742268
Sensitivity :  0.842105263158
Specificity :  0.275
0.814432989691

In [45]:
from sklearn import tree

kf = KFold(n_splits=10)
acc = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    clf = tree.DecisionTreeClassifier().fit(X_train_scaled, y_train)
    score = clf.score(X_test_scaled, y_test)
    acc.append(score)
    y_pred = clf.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(accuracy1)
#     sens.append(sensitivity1)
#     spec.append(specificity1)
    
# mean_acc = sum(acc)/len(acc)
# mean_sens = sum(sens)/len(sens)
# mean_spec = sum(spec)/len(spec)
print(max(acc))

Confusion Matrix : 
 [[18 42]
 [11  7]]
Accuracy :  0.320512820513
Sensitivity :  0.3
Specificity :  0.388888888889
Confusion Matrix : 
 [[ 1 39]
 [ 8 30]]
Accuracy :  0.397435897436
Sensitivity :  0.025
Specificity :  0.789473684211
Confusion Matrix : 
 [[31 29]
 [11  7]]
Accuracy :  0.487179487179
Sensitivity :  0.516666666667
Specificity :  0.388888888889
Confusion Matrix : 
 [[12  0]
 [58  8]]
Accuracy :  0.25641025641
Sensitivity :  1.0
Specificity :  0.121212121212
Confusion Matrix : 
 [[33 15]
 [29  1]]
Accuracy :  0.435897435897
Sensitivity :  0.6875
Specificity :  0.0333333333333
Confusion Matrix : 
 [[ 7 21]
 [18 32]]
Accuracy :  0.5
Sensitivity :  0.25
Specificity :  0.64
Confusion Matrix : 
 [[38 20]
 [ 0 20]]
Accuracy :  0.74358974359
Sensitivity :  0.655172413793
Specificity :  1.0
Confusion Matrix : 
 [[16 18]
 [ 0 44]]
Accuracy :  0.769230769231
Sensitivity :  0.470588235294
Specificity :  1.0
Confusion Matrix : 
 [[25 35]
 [ 0 18]]
Accuracy :  0.551282051282
Sensitivit

In [46]:
from sklearn.neural_network import MLPClassifier

kf = KFold(n_splits=10)
acc = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    clf = MLPClassifier(random_state=0, max_iter=5000, alpha=0.001, hidden_layer_sizes=(10,2)).fit(X_train_scaled, y_train)
    score = clf.score(X_test_scaled, y_test)
    y_pred = clf.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(score)
    
# mean_acc = sum(acc)/len(acc)
# mean_sens = sum(sens)/len(sens)
# mean_spec = sum(spec)/len(spec)
print(max(acc))

Confusion Matrix : 
 [[30 30]
 [ 3 15]]
Accuracy :  0.576923076923
Sensitivity :  0.5
Specificity :  0.833333333333
Confusion Matrix : 
 [[23 17]
 [22 16]]
Accuracy :  0.5
Sensitivity :  0.575
Specificity :  0.421052631579
Confusion Matrix : 
 [[39 21]
 [11  7]]
Accuracy :  0.589743589744
Sensitivity :  0.65
Specificity :  0.388888888889
Confusion Matrix : 
 [[11  1]
 [56 10]]
Accuracy :  0.269230769231
Sensitivity :  0.916666666667
Specificity :  0.151515151515
Confusion Matrix : 
 [[41  7]
 [26  4]]
Accuracy :  0.576923076923
Sensitivity :  0.854166666667
Specificity :  0.133333333333
Confusion Matrix : 
 [[27  1]
 [10 40]]
Accuracy :  0.858974358974
Sensitivity :  0.964285714286
Specificity :  0.8
Confusion Matrix : 
 [[42 16]
 [16  4]]
Accuracy :  0.589743589744
Sensitivity :  0.724137931034
Specificity :  0.2
Confusion Matrix : 
 [[29  5]
 [22 22]]
Accuracy :  0.653846153846
Sensitivity :  0.852941176471
Specificity :  0.5
Confusion Matrix : 
 [[33 27]
 [ 7 11]]
Accuracy :  0.5641